//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MojaNawigacja.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NawigacjaDatabaseEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NawigacjaDatabaseEntities1 object using the connection string found in the 'NawigacjaDatabaseEntities1' section of the application configuration file.
        /// </summary>
        public NawigacjaDatabaseEntities1() : base("name=NawigacjaDatabaseEntities1", "NawigacjaDatabaseEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NawigacjaDatabaseEntities1 object.
        /// </summary>
        public NawigacjaDatabaseEntities1(string connectionString) : base(connectionString, "NawigacjaDatabaseEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NawigacjaDatabaseEntities1 object.
        /// </summary>
        public NawigacjaDatabaseEntities1(EntityConnection connection) : base(connection, "NawigacjaDatabaseEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Adresy> Adresy
        {
            get
            {
                if ((_Adresy == null))
                {
                    _Adresy = base.CreateObjectSet<Adresy>("Adresy");
                }
                return _Adresy;
            }
        }
        private ObjectSet<Adresy> _Adresy;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Adresy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdresy(Adresy adresy)
        {
            base.AddObject("Adresy", adresy);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NawigacjaDatabaseModel", Name="Adresy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Adresy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Adresy object.
        /// </summary>
        /// <param name="idTrasy">Initial value of the IdTrasy property.</param>
        public static Adresy CreateAdresy(global::System.Int32 idTrasy)
        {
            Adresy adresy = new Adresy();
            adresy.IdTrasy = idTrasy;
            return adresy;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTrasy
        {
            get
            {
                return _IdTrasy;
            }
            set
            {
                if (_IdTrasy != value)
                {
                    OnIdTrasyChanging(value);
                    ReportPropertyChanging("IdTrasy");
                    _IdTrasy = StructuralObject.SetValidValue(value, "IdTrasy");
                    ReportPropertyChanged("IdTrasy");
                    OnIdTrasyChanged();
                }
            }
        }
        private global::System.Int32 _IdTrasy;
        partial void OnIdTrasyChanging(global::System.Int32 value);
        partial void OnIdTrasyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiejsceWyjazdu
        {
            get
            {
                return _MiejsceWyjazdu;
            }
            set
            {
                OnMiejsceWyjazduChanging(value);
                ReportPropertyChanging("MiejsceWyjazdu");
                _MiejsceWyjazdu = StructuralObject.SetValidValue(value, true, "MiejsceWyjazdu");
                ReportPropertyChanged("MiejsceWyjazdu");
                OnMiejsceWyjazduChanged();
            }
        }
        private global::System.String _MiejsceWyjazdu;
        partial void OnMiejsceWyjazduChanging(global::System.String value);
        partial void OnMiejsceWyjazduChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiejsceDocelowe
        {
            get
            {
                return _MiejsceDocelowe;
            }
            set
            {
                OnMiejsceDoceloweChanging(value);
                ReportPropertyChanging("MiejsceDocelowe");
                _MiejsceDocelowe = StructuralObject.SetValidValue(value, true, "MiejsceDocelowe");
                ReportPropertyChanged("MiejsceDocelowe");
                OnMiejsceDoceloweChanged();
            }
        }
        private global::System.String _MiejsceDocelowe;
        partial void OnMiejsceDoceloweChanging(global::System.String value);
        partial void OnMiejsceDoceloweChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataDodania
        {
            get
            {
                return _DataDodania;
            }
            set
            {
                OnDataDodaniaChanging(value);
                ReportPropertyChanging("DataDodania");
                _DataDodania = StructuralObject.SetValidValue(value, "DataDodania");
                ReportPropertyChanged("DataDodania");
                OnDataDodaniaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataDodania;
        partial void OnDataDodaniaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataDodaniaChanged();

        #endregion

    }

    #endregion

}
