//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EDeklaracje_WebService.Core.BramkaWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UslugiUBDSoap11", Namespace="http://www.mf.gov.pl/uslugiBiznesowe/DI/UslugiUBD/2013/11/05")]
    public partial class UslugiUBD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WyslijDokumentZbiorczyOperationCompleted;
        
        private System.Threading.SendOrPostCallback PobierzUpoOperationCompleted;
        
        private System.Threading.SendOrPostCallback WyslijNiepodpisanyDokumentZbiorczyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UslugiUBD() {
            this.Url = global::EDeklaracje_WebService.Core.Properties.Settings.Default.EDeklaracje_WebService_Core_BramkaWebReference_UslugiUBD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WyslijDokumentZbiorczyCompletedEventHandler WyslijDokumentZbiorczyCompleted;
        
        /// <remarks/>
        public event PobierzUpoCompletedEventHandler PobierzUpoCompleted;
        
        /// <remarks/>
        public event WyslijNiepodpisanyDokumentZbiorczyCompletedEventHandler WyslijNiepodpisanyDokumentZbiorczyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:WyslijDokumentZbiorczy", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("WyslijDokumentZbiorczyOdpowiedz", Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
        public DokumentOdpowiedz WyslijDokumentZbiorczy([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")] DokumentPytanie WyslijDokumentZbiorczyPytanie) {
            object[] results = this.Invoke("WyslijDokumentZbiorczy", new object[] {
                        WyslijDokumentZbiorczyPytanie});
            return ((DokumentOdpowiedz)(results[0]));
        }
        
        /// <remarks/>
        public void WyslijDokumentZbiorczyAsync(DokumentPytanie WyslijDokumentZbiorczyPytanie) {
            this.WyslijDokumentZbiorczyAsync(WyslijDokumentZbiorczyPytanie, null);
        }
        
        /// <remarks/>
        public void WyslijDokumentZbiorczyAsync(DokumentPytanie WyslijDokumentZbiorczyPytanie, object userState) {
            if ((this.WyslijDokumentZbiorczyOperationCompleted == null)) {
                this.WyslijDokumentZbiorczyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWyslijDokumentZbiorczyOperationCompleted);
            }
            this.InvokeAsync("WyslijDokumentZbiorczy", new object[] {
                        WyslijDokumentZbiorczyPytanie}, this.WyslijDokumentZbiorczyOperationCompleted, userState);
        }
        
        private void OnWyslijDokumentZbiorczyOperationCompleted(object arg) {
            if ((this.WyslijDokumentZbiorczyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WyslijDokumentZbiorczyCompleted(this, new WyslijDokumentZbiorczyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:PobierzUpo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PobierzUpoOdpowiedz", Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
        public PobierzUpoOdpowiedz PobierzUpo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")] PobierzUpoPytanie PobierzUpoPytanie) {
            object[] results = this.Invoke("PobierzUpo", new object[] {
                        PobierzUpoPytanie});
            return ((PobierzUpoOdpowiedz)(results[0]));
        }
        
        /// <remarks/>
        public void PobierzUpoAsync(PobierzUpoPytanie PobierzUpoPytanie) {
            this.PobierzUpoAsync(PobierzUpoPytanie, null);
        }
        
        /// <remarks/>
        public void PobierzUpoAsync(PobierzUpoPytanie PobierzUpoPytanie, object userState) {
            if ((this.PobierzUpoOperationCompleted == null)) {
                this.PobierzUpoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzUpoOperationCompleted);
            }
            this.InvokeAsync("PobierzUpo", new object[] {
                        PobierzUpoPytanie}, this.PobierzUpoOperationCompleted, userState);
        }
        
        private void OnPobierzUpoOperationCompleted(object arg) {
            if ((this.PobierzUpoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzUpoCompleted(this, new PobierzUpoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:WyslijNiepodpisanyDokumentZbiorczy", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("WyslijNiepodpisanyDokumentZbiorczyOdpowiedz", Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
        public DokumentOdpowiedz WyslijNiepodpisanyDokumentZbiorczy([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")] DokumentPytanie WyslijNiepodpisanyDokumentZbiorczyPytanie) {
            object[] results = this.Invoke("WyslijNiepodpisanyDokumentZbiorczy", new object[] {
                        WyslijNiepodpisanyDokumentZbiorczyPytanie});
            return ((DokumentOdpowiedz)(results[0]));
        }
        
        /// <remarks/>
        public void WyslijNiepodpisanyDokumentZbiorczyAsync(DokumentPytanie WyslijNiepodpisanyDokumentZbiorczyPytanie) {
            this.WyslijNiepodpisanyDokumentZbiorczyAsync(WyslijNiepodpisanyDokumentZbiorczyPytanie, null);
        }
        
        /// <remarks/>
        public void WyslijNiepodpisanyDokumentZbiorczyAsync(DokumentPytanie WyslijNiepodpisanyDokumentZbiorczyPytanie, object userState) {
            if ((this.WyslijNiepodpisanyDokumentZbiorczyOperationCompleted == null)) {
                this.WyslijNiepodpisanyDokumentZbiorczyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWyslijNiepodpisanyDokumentZbiorczyOperationCompleted);
            }
            this.InvokeAsync("WyslijNiepodpisanyDokumentZbiorczy", new object[] {
                        WyslijNiepodpisanyDokumentZbiorczyPytanie}, this.WyslijNiepodpisanyDokumentZbiorczyOperationCompleted, userState);
        }
        
        private void OnWyslijNiepodpisanyDokumentZbiorczyOperationCompleted(object arg) {
            if ((this.WyslijNiepodpisanyDokumentZbiorczyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WyslijNiepodpisanyDokumentZbiorczyCompleted(this, new WyslijNiepodpisanyDokumentZbiorczyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DokumentZalacznikBinarnyPytanie))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
    public partial class DokumentPytanie {
        
        private byte[] dokumentField;
        
        private DokumentPytanieJezyk jezykField;
        
        private bool jezykFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Dokument {
            get {
                return this.dokumentField;
            }
            set {
                this.dokumentField = value;
            }
        }
        
        /// <remarks/>
        public DokumentPytanieJezyk Jezyk {
            get {
                return this.jezykField;
            }
            set {
                this.jezykField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JezykSpecified {
            get {
                return this.jezykFieldSpecified;
            }
            set {
                this.jezykFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
    public enum DokumentPytanieJezyk {
        
        /// <remarks/>
        de,
        
        /// <remarks/>
        en,
        
        /// <remarks/>
        pl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
    public partial class DokumentOdpowiedz {
        
        private string refIdField;
        
        private int statusField;
        
        private string statusOpisField;
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string statusOpis {
            get {
                return this.statusOpisField;
            }
            set {
                this.statusOpisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
    public partial class DokumentZalacznikBinarnyPytanie : DokumentPytanie {
        
        private byte[] zalacznikField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Zalacznik {
            get {
                return this.zalacznikField;
            }
            set {
                this.zalacznikField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
    public partial class PobierzUpoPytanie {
        
        private string numerReferencyjnyField;
        
        private PobierzUpoPytanieJezyk jezykField;
        
        private bool jezykFieldSpecified;
        
        /// <remarks/>
        public string NumerReferencyjny {
            get {
                return this.numerReferencyjnyField;
            }
            set {
                this.numerReferencyjnyField = value;
            }
        }
        
        /// <remarks/>
        public PobierzUpoPytanieJezyk Jezyk {
            get {
                return this.jezykField;
            }
            set {
                this.jezykField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JezykSpecified {
            get {
                return this.jezykFieldSpecified;
            }
            set {
                this.jezykFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
    public enum PobierzUpoPytanieJezyk {
        
        /// <remarks/>
        de,
        
        /// <remarks/>
        en,
        
        /// <remarks/>
        pl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.mf.gov.pl/schematy/DI/UslugiUBD/2013/11/05")]
    public partial class PobierzUpoOdpowiedz {
        
        private string upoField;
        
        private int statusField;
        
        private string statusOpisField;
        
        /// <remarks/>
        public string Upo {
            get {
                return this.upoField;
            }
            set {
                this.upoField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusOpis {
            get {
                return this.statusOpisField;
            }
            set {
                this.statusOpisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void WyslijDokumentZbiorczyCompletedEventHandler(object sender, WyslijDokumentZbiorczyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WyslijDokumentZbiorczyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WyslijDokumentZbiorczyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DokumentOdpowiedz Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DokumentOdpowiedz)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PobierzUpoCompletedEventHandler(object sender, PobierzUpoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzUpoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzUpoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PobierzUpoOdpowiedz Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PobierzUpoOdpowiedz)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void WyslijNiepodpisanyDokumentZbiorczyCompletedEventHandler(object sender, WyslijNiepodpisanyDokumentZbiorczyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WyslijNiepodpisanyDokumentZbiorczyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WyslijNiepodpisanyDokumentZbiorczyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DokumentOdpowiedz Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DokumentOdpowiedz)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591